apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: motds.motd.example.com
spec:
  group: motd.example.com
  names:
    kind: MOTD
    listKind: MOTDList
    plural: motds
    singular: motd
  scope: Namespaced
  version: v1
  subresources:
    status: {}
